version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run: python3 test_hello_world.py

  test:
    working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run: python3 test_hello_world.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build