version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run: python3 tests/python/test_hello_world.py

  test:
    working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run: python3 tests/python/test_hello_world.py

  codecept_testing_suite:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout

      # - run:
      #     name: Install Docker Client
      #     command: |
      #       sudo apt-get remove docker docker-engine docker.io containerd runc -y
      #       sudo apt-get update
      #       sudo apt-get install docker docker-ce docker-ce-cli containerd.io -y

      - run:
          name: Install Docker Compose
          command: |
            set -x
            sudo rm /usr/local/bin/docker-compose
            sudo curl -L "https://github.com/docker/compose/releases/download/1.28.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Start Application Cluster
          command: |
            set -x
            cd docker
            docker-compose up -d

      - run:
          name: Run Codeception Testing Suite
          command: |
            # docker exec -it -u 0 docker_codecept_1 ls /project/codeception/
            # docker exec -it -u 0 docker_codecept_1 chmod 755 /project/codeception/
            docker exec -it docker_codecept_1 lslogins -u
            docker exec -it --user root docker_codecept_1 codecept bootstrap
            docker exec -it --user root docker_codecept_1 codecept run

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
  testing_suite:
    jobs:
      - codecept_testing_suite
