version: 2.1

orbs:
  kubernetes: digitalocean/k8s@0.1.1
  digitalocean: digitalocean/cli@0.1.1
  docker: circleci/docker@1.5.0

jobs:
  # Codeception:
  #   machine: 
  #     image: ubuntu-2004:202101-01
  #   steps:
  #     - checkout
  #     - run: 
  #         name: Initialise Containers and Test Web App
  #         command: |
  #           set -x
  #           cd docker
  #           docker-compose up -d
  #           sleep 40
  #           docker-compose run --rm codecept
  # Python:
  #   working_directory: ~/circleci-python
  #   docker:
  #     - image: cimg/python:3.9.1
  #   steps:
  #     - checkout
  #     - run: python3 tests/python/test_hello_world.py
  # VisualRegression:
  #   machine: 
  #     image: ubuntu-2004:202101-01
  #   steps:
  #     - checkout
  #     - run: 
  #         name: Initialize containers and Check Visual Regression
  #         command: |
  #           set -x
  #           cd docker
  #           docker-compose up -d
  #           sleep 10
  #           docker-compose run visual_regression_tests test
  Deploy_to_k8s:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - kubernetes/install
      - kubernetes/initialize:
          cluster: music2score-k8s-test
      # - digitalocean/install
      # - digitalocean/initialize
          # digitalocean-access-token: ${DIGITALOCEAN_ACCESS_TOKEN}
          # cluster: music2score-k8s-test
      - run: doctl kubernetes cluster kubeconfig save music2score-k8s-test
      # - run: cd ~/.kube && kubectl --kubeconfig="music2score-k8s-test-kubeconfig.yaml" get nodes
      - run: kubectl apply -f k8s/
      - run: kubectl rollout restart deployment apache-server --namespace=music2score
      - run: kubectl rollout restart deployment mysql-server --namespace=music2score


workflows:
  Pipeline:
    jobs:
      # - Codeception
      # - Python
      # - VisualRegression
      - Deploy_to_k8s:
          context: DigitalOcean
          # requires:
          #   - Codeception
          #   - Python
          #   - VisualRegression
          filters:
            branches:
              only:
                - main
                - deployment_cd