version: 2.1

jobs:
  Codeception:
    machine: 
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: 
          name: Initialise Containers and Test Web App
          command: |
            set -x
            sudo chmod 777 pages/uploads
            cd docker
            docker-compose up -d
            docker-compose kill codecept 
            sleep 40
            docker-compose run --rm codecept
  Python:
    machine: 
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Initialize and Run pytest container
          command: |
            set -x
            cd docker
            docker-compose up -d
            docker-compose kill codecept
            sleep 60
            docker-compose run --rm pytest
  VisualRegression:
    machine: 
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: 
          name: Initialize containers and Check Visual Regression
          command: |
            set -x
            mv codeception/bin/_data/1_20210314_050829893404_6164539564972943 pages/uploads
            cd docker
            docker-compose up -d
            docker-compose kill codecept
            sleep 20
            docker exec -i docker_mysql_server_1 mysql -u root -p12345 < ../backstopJS/vrt_test_data.sql
            sleep 10
            docker-compose run visual_regression_tests test

workflows:
  Testing:
    jobs:
      - Codeception
      - Python
      - VisualRegression