version: 2.1

jobs:
  # Codeception:
  #   machine: 
  #     image: ubuntu-2004:202101-01
  #   steps:
  #     - checkout
  #     - run: 
  #         name: Initialise Containers and Test Web App
  #         command: |
  #           set -x
  #           cd docker
  #           docker-compose up -d
  #           sleep 40
  #           docker-compose run --rm codecept
  Python:
    docker:
      - image: cimg/base:2021.03
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Initialize and Run pytest container
          command: |
            set -x
            cd docker
            docker-compose run --rm pytest pytest -v
  # VisualRegression:
  #   machine: 
  #     image: ubuntu-2004:202101-01
  #   steps:
  #     - checkout
  #     - run: 
  #         name: Initialize containers and Check Visual Regression
  #         command: |
  #           set -x
  #           cd docker
  #           docker-compose up -d
  #           sleep 10
  #           docker-compose run visual_regression_tests test

workflows:
  Testing:
    jobs:
      # - Codeception
      - Python
      # - VisualRegression