version: 2.1

jobs:
  Codeception:
    machine: 
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: 
          name: Initialise Containers and Test Web App
          command: |
            set -x
            cd docker
            docker-compose up -d
            sleep 40
            docker-compose run --rm codecept
  Python:
    machine: 
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Initialize and Run pytest container
          command: |
            set -x
            cd docker
            docker-compose up -d
            sleep 25
            docker-compose run --rm pytest
  VisualRegression:
    machine: 
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: 
          name: Initialize containers and Check Visual Regression
          command: |
            set -x
            cd docker
            docker-compose up -d
            sleep 10
            docker-compose run visual_regression_tests test

workflows:
  Testing:
    jobs:
      - Codeception
      - Python
      - VisualRegression