version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run: python3 tests/python/test_hello_world.py

  test:
    working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run: python3 tests/python/test_hello_world.py

  codecept_testing_suite:
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.2
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - run:
          name: Start Application Cluster
          command: |
            set -x
            cd docker
            docker-compose up -d

      - run:
          name: Run Codeception Testing Suite
          command: |
            docker exec -w="/project/codeception" -it docker_codecept_1 codecept run

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
  testing_suite:
    jobs:
      - codecept_testing_suite
