version: 2.1

jobs:
  Codeception:
    machine: 
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: 
          name: Initialise Containers and Test Web App
          command: |
            set -x
            cd docker
            docker-compose up -d
            sleep 20
            docker-compose run --rm codecept run -c codeception/
  Python:
    working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run: python3 tests/python/test_hello_world.py

workflows:
  Testing:
    jobs:
      - Codeception
      - Python