version: "3.8"
services:
 apache_server:
  build:
   context: ../
   dockerfile: docker/Dockerfile
  volumes:
   - ../pages/:/var/www/html
   - ../php_config/:/usr/local/etc/php/
   - ../pages/uploads/:/var/www/html/uploads/
  links:
   - mysql_server:mysql_server
  ports:
   - 80:80
 mysql_server:
  image: mysql:8.0.23
  command: --default-authentication-plugin=mysql_native_password --init-file="/tmp/database/schema.sql"
  volumes:
   - ../mysql/test/:/tmp/database/
  environment:
   MYSQL_ROOT_PASSWORD: 12345
   MYSQL_DATABASE: music2score_test
  ports:
   - 3306:3306
  healthcheck:
   test: ["CMD", "mysql", "-uroot", "-p12345", "-hmysql_server"]
   interval: 10s
   timeout: 10s
   retries: 6
 lilypond_server:
  build:
   context: ../
   dockerfile: docker/Dockerfile3
  volumes:
   - ../python/:/python/
  entrypoint: ["python", "./python/polling.py"]
  depends_on:
   mysql_server:
    condition: service_healthy
  links:
   - apache_server:apache_server
   - mysql_server:mysql_server
  ports:
   - 3000:3000
 phpmyadmin:
  depends_on:
   - mysql_server
  image: phpmyadmin/phpmyadmin:5.0.1
  restart: always
  ports:
   - "8081:80"
  environment:
   PMA_HOST: mysql_server
   MYSQL_ROOT_PASSWORD: 12345
 codecept:
  build:
   context: ../
   dockerfile: docker/Dockerfile2
  depends_on:
   - chrome
   - apache_server
   - mysql_server
   - phpmyadmin
   - lilypond_server
  volumes:
   - ../:/project
  links:
   - apache_server:apache_server
 chrome:
  image: selenium/standalone-chrome
  links:
   - apache_server:apache_server
 visual_regression_tests:
  image: backstopjs/backstopjs:latest
  volumes:
   - ../backstopJS/:/src
  links:
   - apache_server:apache_server
  depends_on:
   - apache_server
   - mysql_server
   - lilypond_server
 pytest:
  build:
   context: ../
   dockerfile: docker/Dockerfile4
  volumes: 
   - ../python/:/project/python/
   - ../tests/:/project/tests/
  links:
   - mysql_server:mysql_server
  depends_on:
   - mysql_server
   - lilypond_server
